[project]
name = "homelink-integration-api"
version = "0.1.0"
authors = [
  { name="Gentex Cloud Services", email="cloudservices@gentex.com" },
]
description = "API to interact with HomeLink cloud for MQTT-enabled smart home platforms"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["python-decouple>=3.8", "boto3"]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
asyncio_default_fixture_loop_scope = "function"

[project.urls]
Homepage = "https://www.homelink.com/"
Issues = "https://www.homelink.com/support"
Repository = "https://github.com/Gentex-Corporation/homelink-integration-api"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
